pages livraison et paiement
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G2-feet-n-fun pull request #17
Opened 2024-04-15 12:28 UTC by EmilieLgt

2024-04-15 12:44 UTC, fantinerudent commented on client/src/components/Delivery.jsx
> +/* props : totalPrice */
?

2024-04-15 12:45 UTC, fantinerudent commented on client/src/components/Delivery.jsx
> +  /* afficher la page paiement une fois le formulaire rempli */
comments in English please

2024-04-15 12:45 UTC, fantinerudent commented on client/src/components/Delivery.jsx
> +
useless empty line

2024-04-15 12:45 UTC, fantinerudent commented on client/src/components/Delivery.jsx
> +
useless empty line

2024-04-15 12:46 UTC, fantinerudent commented on client/src/components/Payment.jsx
> +nom, prénom, adresse mail du formulaire livraison (pour confirmation : Merci Bidule Dupont, un e-mail de confirmation avec votre commande ... )
comments in English

2024-04-15 12:47 UTC, fantinerudent commented on client/src/components/deliverypayment.css
> +.containerInputNumber {
space between your classes

2024-04-15 12:47 UTC, fantinerudent requested changes
rien de bloquant à proprement parler, juste besoin d'un peu plus de rigueur dans l'indentation.
+ commentaires en anglais stp ! :)

2024-04-15 14:34 UTC, alexoualexandre approved these changes

2024-04-16 10:45 UTC, fantinerudent approved these changes

2024-04-16 12:06 UTC, merged