Fixing animation open/close
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G2-feet-n-fun pull request #25
Opened 2024-04-18 10:27 UTC by iSayZ

2024-04-18 12:05 UTC, fantinerudent requested changes

2024-04-18 12:05 UTC, fantinerudent commented on client/src/components/Header/Navbar.jsx
> +      {/* {visible ? <BurgerMenu handleToggle={handleToggle} visible={visible} /> : <BurgerMenu handleToggle={handleToggle} visible={visible} />} */}
you can delete this line

2024-04-18 12:07 UTC, EmilieLgt approved these changes

2024-04-18 14:21 UTC, iSayZ commented on client/src/components/Header/Navbar.jsx
> +      {/* {visible ? <BurgerMenu handleToggle={handleToggle} visible={visible} /> : <BurgerMenu handleToggle={handleToggle} visible={visible} />} */}
I have delete this ;)

2024-04-19 09:51 UTC, fantinerudent approved these changes

2024-04-19 10:14 UTC, merged