Search.bar
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G2-feet-n-fun pull request #33
Opened 2024-04-20 06:44 UTC by iSayZ

2024-04-22 08:22 UTC, EmilieLgt approved these changes

2024-04-23 13:16 UTC, fantinerudent requested changes
beaucoup de wording à revoir, et du code mort à supprimer

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Header/SearchBar/SearchBar.jsx
> +  // const searchItem = (value) => {
😠

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Header/SearchBar/SearchBar.jsx
> +        {/* <button type="button" className="btn-search" onClick={() => searchItem(inputValue)}> */}
😠

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Shop/Card/CardContainerSearch/CardContainerSearch.jsx
> +  // State qui stock l'état Ouvert/Fermé du composant ProductDetails
qui stocke*

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Shop/Card/CardContainerSearch/CardContainerSearch.jsx
> +  // State qui stock la taille choisit pour l'ajout au panier
stocke, choisie*

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Shop/Card/CardContainerSearch/CardContainerSearch.jsx
> +        {/* .map() Pour générer toutes les cards d'une section */}
pas nécessaire

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Shop/Card/CardContainerSearch/CardContainerSearch.jsx
> +      {/* Ouvre le composant ProductDetails lors ce que visible est true */}
et le tableau de date n'est pas vide , mettez toutes les explications ou alors le commentaire n'a pas vraiment d'utilité.

2024-04-23 13:16 UTC, fantinerudent commented on client/src/components/Shop/Card/ProductDetails/ProductDetails.jsx
>    // Function qui assigne la taille sélectionner au state chooseSize (dans le composant CardContainer) pour transmettre la taille lors de l'ajout au panier.
fonction, sélectionnée*

2024-04-23 13:16 UTC, fantinerudent commented on client/src/pages/Search.jsx
> +        // ici j'obtient un tableau contenant les 5 tableaux products de chaque cat
catégories

2024-04-23 13:16 UTC, fantinerudent commented on client/src/pages/Search.jsx
> +
ça mériterait pas un petit commentaire tout ce useLocation params ect?  :)

2024-04-24 09:31 UTC, closed without merging