Création d'un context provider, ajout des fonctionnalités d'ajout au panier, calcul du prix et de la taille
WildCodeSchool-2024-02/JS-LILLE-0224-P2-G2-feet-n-fun pull request #36
Opened 2024-04-23 14:18 UTC by EmilieLgt

2024-04-23 14:55 UTC, alexoualexandre approved these changes

2024-04-23 15:36 UTC, fantinerudent requested changes

2024-04-23 15:36 UTC, fantinerudent commented on client/src/main.jsx
>  // Le useEffect fait un appel d'API au démarrage de la page et stock le resultat dans le state "data"
a supprimer

2024-04-23 15:36 UTC, fantinerudent commented on client/src/components/Cart/CartCard.jsx
> +  const prixProduit2 = prixProduit.toFixed(2);
rename

2024-04-23 15:36 UTC, fantinerudent commented on client/src/components/Cart/CartContainer.jsx
> +    let totalAmount2 = 0;
rename

2024-04-23 15:36 UTC, fantinerudent commented on client/src/components/Shop/Card.jsx
>      // ENLEVER LE ROLE BUTTON ET TABINDEX UNE FOIS QUE LE ONCLICK SERA SUR LES ELEMENTS QUI IRONS VERS LE PRODUCTDETAILS
c'est réglé ça?

2024-04-23 15:36 UTC, fantinerudent commented on client/src/components/Shop/Card.jsx
> +            <img src="../public/assets/images/icons/cart4.svg" alt="favoris" />
je crois que tu as pas besoin des .. devant le / du dossier public

2024-04-23 15:36 UTC, fantinerudent commented on client/src/context/ShopContext.jsx
> +  const contextValue = useMemo(
pourquoi l'utilisation d'un useMemo?

2024-04-23 15:36 UTC, fantinerudent commented on client/src/main.jsx
> +      { path: "/a-propos", element: <About />, loader: () => getData() },
Joker...

2024-04-23 15:36 UTC, fantinerudent commented on client/src/pages/Panier.jsx
>  function Panier() {
could you rename in English this component, the only one in french 🥹

2024-04-24 10:16 UTC, fantinerudent requested changes

2024-04-24 10:16 UTC, fantinerudent commented on client/src/components/Cart/CartContainer.jsx
> +     on ajoute au total la quanité multipliée par le prix (récupéré de l'API, noté product.price)
quantité

2024-04-24 10:16 UTC, fantinerudent commented on client/src/components/Cart/Favoris/favoris.css
> +.titleRubrique {
franglish

2024-04-24 10:16 UTC, fantinerudent commented on client/src/components/Shop/CardContainer.jsx
> +      <h2 className="titreCategorie">{data.name}</h2>
category title

2024-04-24 10:16 UTC, fantinerudent commented on client/src/context/ShopContext.jsx
> +  /* Les state qui contiennent les id des éléments du panier et des favoris */
states

2024-04-24 10:16 UTC, fantinerudent commented on client/src/pages/Favoris.jsx
>  function Favoris() {
Favorites je crois

2024-04-24 10:16 UTC, fantinerudent commented on client/src/pages/Favoris.jsx
> +  return <FavorisContainer data={data} />;
Favorites container

2024-04-24 15:02 UTC, fantinerudent requested changes

2024-04-24 15:02 UTC, fantinerudent commented on client/src/components/Cart/CartContainer.jsx
> +    - totalAmount : stock le prix total du panier
stocke

2024-04-24 15:02 UTC, fantinerudent commented on client/src/components/Header/NavBar/Navbar.jsx
> +          <div className="groupeBoutonsNav">
groupButtons

2024-04-24 15:02 UTC, fantinerudent commented on client/src/context/ShopContext.jsx
> +  // State qui stock l'état Ouvert/Fermé du composant ProductDetails
stocke

2024-04-24 15:02 UTC, fantinerudent commented on client/src/context/ShopContext.jsx
> +  /* const addToCart = (itemId) => {
CODE MORT

2024-04-24 15:03 UTC, fantinerudent commented on client/src/context/ShopContext.jsx
> +  const contextValue = useMemo(
@EmilieLgt  du coup ? :)

2024-04-24 15:18 UTC, rocambille requested changes

2024-04-24 15:18 UTC, rocambille commented on client/src/components/Cart/CartContainer.jsx
> +  let totalAmount = 0;
à déplacer dans la fonction getTotalCarAmount : il ne sert pas en dehors ;)

2024-04-24 15:18 UTC, rocambille commented on client/src/components/Cart/CartCard.jsx
> +        <input value={quantity} />
type="number" min="1"

2024-04-24 15:18 UTC, rocambille commented on client/src/components/Cart/CartContainer.jsx
> +            <button type="button" className="cartValidationButton">
pas de bouton dans un lien : un lien peut avoir le style d'un bouton, et un bouton le style d'un lien mais c'est le rôle du CSS pas du HTML

https://codepen.io/rocambille/pen/zYGQXaV

2024-04-24 15:18 UTC, rocambille commented on client/src/components/Cart/FavorisContainer.jsx
> +    return foundProduct;
const findProductById = (productId) => {
      return  category.products.find(
        (product) => product.id === productId
      );
    };

?

2024-04-24 15:18 UTC, rocambille commented on package.json
> +    "react-router-dom": "^6.22.3"
La racine du projet n'a pas besoin de react-router-dom, c'est le dossier client qui en a besoin : à restaurer ;)

2024-04-24 15:22 UTC, fantinerudent commented on package.json
> +    "react-router-dom": "^6.22.3"
@rocambille  comment le linter a laissé passer ça ? ça passe jamais d'habitude

2024-04-24 15:29 UTC, rocambille commented on package.json
> +    "react-router-dom": "^6.22.3"
Une personne l'a court-circuité j'imagine

2024-04-25 08:29 UTC, rocambille commented
Conflits à résoudre :)

2024-04-25 14:19 UTC, rocambille requested changes

2024-04-25 14:19 UTC, rocambille commented on client/src/components/Cart/Cart/CartContainer.jsx
> +  };
Toujours ce code à changer : beaucoup de choses qui ne servent pas dedans.

    const findProductById = (productId) => {
      return  category.products.find(
        (product) => product.id === productId
      );
    };

Et le eslint disable ne devrait pas être là (je crois d'ailleurs qu'il provoque l'erreur "report-unused-disable-directives" dans les vérif eslint)

2024-04-25 15:39 UTC, merged